const ALL_VIDEOGAMES = "ALL_VIDEOGAMES";
const VIDEOGAME_DETAILS = "GAME_DETAILS";
const VIDEOGAME_BY_NAME = "VIDEOGAME_BY_NAME";
const NEW_VIDEOGAME = "NEW_VIDEOGAME";
const GENRES = "GENRES";
const FILTER = "FILTER";

module.exports={
    ALL_VIDEOGAMES,
    VIDEOGAME_DETAILS,
    VIDEOGAME_BY_NAME,
    NEW_VIDEOGAME,
    GENRES,
    FILTER,
}